Repository kartoza/django-bims, pull requests merged in 2018-10, with the labels that each got.

#388 Add reference category filter
  bims/api_views/collection.py
  bims/api_views/reference_category.py
  bims/api_views/search.py
  bims/indexes/biological_collection_record.py
  bims/static/js/collections/cluster_biological.js
  bims/static/js/collections/reference_category.js
  bims/static/js/collections/search_result.js
  bims/static/js/models/reference_category.js
  bims/static/js/views/filter_panel/reference_category.js
  bims/static/js/views/search.js
  bims/templates/map_page/bims.html
  bims/templates/map_page/map-templates.html
  bims/tests/test_api_views.py
  bims/urls.py
  bims/views/map.py
Labels: in review, review

#389 Fix missing variable
  bims/static/js/collections/cluster_biological.js
Labels: in review, review

#390 Fix csv uploads
  bims/migrations/0044_auto_20181001_0703.py
  bims/models/biological_collection_record.py
  bims/views/csv_upload.py
Labels: in review

#391 Update location site model
  bims/migrations/0044_auto_20181001_0730.py
  bims/models/location_site.py
Labels: in review, review

#392 Validation ui
  bims/api_views/non_validated_record.py
  bims/migrations/0045_merge_20181002_0219.py
  bims/serializers/bio_collection_serializer.py
  bims/static/css/map.css
  bims/static/js/app.js
  bims/static/js/collections/validate_data.js
  bims/static/js/models/validate_data.js
  bims/static/js/optimized.js
  bims/static/js/views/map_control_panel.js
  bims/static/js/views/olmap.js
  bims/static/js/views/right_panel/validate_data_detail.js
  bims/static/js/views/right_panel/validate_data_list.js
  bims/static/js/views/side_panel.js
  bims/templates/main_base.html
  bims/templates/map_page/bims.html
  bims/templates/map_page/map-templates.html
  bims/views/csv_upload.py
  bims/views/map.py
Labels: in review, review

#393 Fix get key function
  bims/utils/get_key.py
Labels: in review

#397 Update search panel
  bims/static/css/map.css
  bims/static/js/app.js
  bims/static/js/views/spatial_filter.js
  bims/templates/map_page/map-templates.html
Labels: in review, review

#398 Running cluster search from worker
  bims/admin.py
  bims/api_views/collection.py
  bims/api_views/search.py
  bims/indexes/biological_collection_record.py
  bims/indexes/location_site.py
  bims/migrations/0046_searchprocess.py
  bims/migrations/0047_auto_20181009_0641.py
  bims/migrations/0048_auto_20181009_0654.py
  bims/migrations/0049_auto_20181011_1033.py
  bims/models/__init__.py
  bims/models/search_process.py
  bims/static/js/collections/cluster_biological.js
  bims/static/js/collections/search_result.js
  bims/static/js/models/cluster_location_site.js
  bims/static/js/views/cluster_biological.js
  bims/static/js/views/cluster_location_site.js
  bims/static/js/views/layer_style.js
  bims/static/js/views/olmap.js
  bims/static/js/views/olmap_layers.js
  bims/static/js/views/political_region.js
  bims/static/js/views/search.js
  bims/static/js/views/search_panel.js
  bims/static/js/views/spatial_filter.js
  bims/tasks/__init__.py
  bims/tasks/cluster.py
  bims/tasks/search.py
  core/settings/dev_docker.py
  deployment/docker-compose.yml
Labels: in review

#404 Fix uglified js
  bims/static/js/collections/cluster_biological.js
  bims/static/js/collections/search_result.js
  bims/static/js/optimized.js
Labels: in review

#405 Fix old clusters not replaced
  bims/static/js/collections/cluster_biological.js
Labels: in review

#406 Fix search site
  bims/api_views/collection.py
Labels: in review

#407 Fix download csv
  bims/static/js/collections/cluster_biological.js
  bims/static/js/collections/search_result.js
  bims/static/js/views/data_downloader-modal.js
Labels: in review, review

#409 Don't returns all data while search working
  bims/static/js/collections/search_result.js
  bims/static/js/landing-page.js
  bims/static/js/optimized.js
  bims/static/js/views/data_downloader-modal.js
  bims/tasks/search.py
Labels: in review, review

#410 Reset total counts
  bims/static/js/collections/search_result.js
Labels: in review

#412 Papercuts
  bims/api_views/collection.py
  bims/api_views/reference_list.py
  bims/indexes/biological_collection_record.py
  bims/management/commands/merge_duplicate_sites.py
  bims/models/biological_collection_record.py
  bims/models/search_process.py
  bims/static/css/map.css
  bims/static/js/app.js
  bims/static/js/collections/cluster_biological.js
  bims/static/js/collections/search_result.js
  bims/static/js/views/filter_panel/reference_category.js
  bims/static/js/views/search.js
  bims/templates/map_page/bims.html
  bims/templates/map_page/map-templates.html
  bims/urls.py
  bims/views/csv_upload.py
  bims/views/map.py
Labels: in review, review

#414 Improve search
  bims/api_views/search.py
  bims/static/js/collections/cluster_biological.js
  bims/static/js/collections/search_result.js
  bims/static/js/models/search_result.js
  bims/static/js/views/right_panel/location_site_detail.js
  bims/static/js/views/search_result.js
  bims/tasks/cluster.py
  bims/tasks/search.py
  bims/templates/map_page/map-templates.html
Labels: in review, review

#415 Download all records if unfiltered
  bims/api_views/collection.py
  bims/api_views/search.py
  bims/tasks/cluster.py
  bims/tasks/collection_record.py
  bims/tasks/search.py
  bims/views/csv_upload.py
Labels: review

#416 Improve csv download
  bims/api_views/collection.py
  bims/static/js/collections/cluster_biological.js
  bims/static/js/views/data_downloader-modal.js
  bims/utils/url.py
Labels: in review, review

#418 Fix missing species list in site detail
  bims/static/js/collections/search_result.js
Labels: in review

#419 Save filter parameters globally
  bims/static/js/collections/cluster_biological.js
  bims/templates/map_page/bims.html
Labels: in review, review

#420 Fix inconsistences site detail
  bims/api_views/collection.py
  bims/api_views/location_site.py
  bims/indexes/biological_collection_record.py
  bims/serializers/location_site_detail_serializer.py
  bims/static/js/views/geocontext.js
  bims/static/js/views/right_panel/location_site_detail.js
  bims/templates/map_page/bims.html
  bims/urls.py
Labels: in review, review

#421 Fix search query
  bims/api_views/collection.py
Labels: in review, review

#423 Return site name
  bims/serializers/bio_collection_serializer.py
Labels: in review

#424 Request GetFeatureInfo from backend
  bims/api_views/get_feature_info.py
  bims/permissions/auth_class.py
  bims/static/js/views/olmap_layers.js
  bims/urls.py
Labels: in review, review

#426 Fix hidden cluster points from search results
  bims/api_views/get_biorecord.py
  bims/api_views/get_feature_info.py
  bims/api_views/location_site.py
  bims/permissions/auth_class.py
  bims/serializers/bio_collection_serializer.py
  bims/static/js/views/olmap_layers.js
Labels: in review, review

#427 Non biodiversity layer ordering
  bims/migrations/0052_nonbiodiversitylayer_default_visibility.py
  bims/models/non_biodiversity_layer.py
  bims/static/js/views/olmap_layers.js
Labels: in review, review

#430 Fix inconsistencies in reporting
  bims/api_views/collection.py
  bims/api_views/get_biorecord.py
  bims/api_views/search.py
Labels: in review

#431 Show origin and endemism
  bims/api_views/taxon.py
  bims/static/css/map.css
  bims/static/js/views/right_panel/taxon_detail.js
  bims/templates/map_page/map-templates.html
Labels: in review, review

#432 Fix basemap names
  bims/static/js/views/olmap_basemap.js
Labels: in review, review

#433 Togglable spatial tree filter
  bims/static/css/map.css
  bims/static/js/views/spatial_filter.js
Labels: in review, review

#434 Add management command to update taxa and iucn
  bims/management/commands/fix_accepted_taxa.py
  bims/management/commands/update_iucn_taxa.py
  bims/migrations/0053_taxon_iucn_redlist_id.py
  bims/migrations/0054_auto_20181019_0915.py
  bims/models/taxon.py
  bims/utils/gbif.py
  bims/utils/iucn.py
Labels: in review, review

#436 Change basemap name and fix select cluster
  bims/static/js/views/olmap.js
  bims/static/js/views/olmap_basemap.js
  bims/static/js/views/right_panel/taxon_detail.js
Labels: in review, review

#438 Fix update filter by taxon
  bims/static/js/collections/cluster_biological.js
  bims/static/js/router.js
  bims/static/js/shared.js
  bims/static/js/utils/events_connector.js
  bims/static/js/views/olmap.js
  bims/static/js/views/search.js
  bims/static/js/views/search_result.js
Labels: in review

#439 Fix csv download by site
  bims/api_views/collection.py
  bims/serializers/bio_collection_serializer.py
  bims/tasks/collection_record.py
Labels: in review, review

#442 Add tooltip to map control panel
  bims/static/js/app.js
  bims/static/js/views/map_control_panel.js
  bims/static/js/views/olmap.js
  bims/templates/map_page/map-templates.html
Labels: in review, review

#444 Easily change site title
  bims/context_processor.py
  bims/templates/_layouts/base.html
  bims/templates/account/login.html
  bims/templates/account/logout.html
  bims/templates/account/password_reset.html
  bims/templates/account/password_reset_done.html
  bims/templates/account/password_reset_from_key.html
  bims/templates/account/password_reset_from_key_done.html
  bims/templates/account/signup.html
  bims/templates/account/verification_sent.html
  bims/templates/contactus/contact.html
  bims/templates/csv_uploader.html
  bims/templates/landing_page.html
  bims/templates/links/links.html
  bims/templates/main_base.html
  bims/templates/shapefile_uploader.html
  bims/templates/tracking/snippets/stats.html
  core/settings/contrib.py
Labels: in review, review

#445 Update locate texts
  bims/static/js/views/locate.js
  bims/templates/map_page/map-templates.html
Labels: in review, review

#447 Fix bootstrap bundle not found
  bims/static/js/app.js
  bims/static/js/optimized.js
Labels: in review

#449 Integrate base map control with main control
  bims/static/css/map.css
  bims/static/js/app.js
  bims/static/js/views/data_downloader.js
  bims/static/js/views/map_control_panel.js
  bims/static/js/views/olmap.js
  bims/templates/map_page/map-templates.html
Labels: in review

#450 Update django to fix vulnerability issue
  bims/management/commands/fix_accepted_taxa.py
  bims/tests/test_api_views.py
  bims/utils/gbif.py
  deployment/docker/REQUIREMENTS.txt
  deployment/production/REQUIREMENTS.txt
  setup.py
Labels: in review, review

#452 Fix layers from geonode not appear
  bims/static/js/views/olmap_layers.js
Labels: in review, review

#453 Update basemap name
  bims/static/js/views/olmap_basemap.js
Labels: in review

#456 Fix legends can't be hidden
  bims/static/css/map.css
  bims/static/js/app.js
  bims/static/js/libs/jquery-ui-1.12.1/jquery-ui.min.css
  bims/static/js/libs/jquery-ui-1.12.1/jquery-ui.min.js
  bims/static/js/libs/jquery-ui-1.12.1/jquery-ui.structure.min.css
  bims/static/js/libs/jquery-ui-1.12.1/jquery-ui.theme.min.css
  bims/static/js/optimized.js
  bims/static/js/shared.js
  bims/static/js/views/olmap.js
  bims/static/js/views/olmap_layers.js
  bims/templates/map_page/map-templates.html
Labels: in review

#458 Do not display geonode theme in profile page
  bims/static/img/groups-default-icon.png
  bims/templates/account/email.html
  bims/templates/account/password_change.html
  bims/templates/main_base.html
  bims/templates/navigation_bar.html
  bims/templates/people/profile_base.html
  bims/templates/people/profile_detail.html
  bims/templates/socialaccount/base.html
  bims/templates/socialaccount/connections.html
Labels: in review, review

#460 Makes sure data from geonode group profile is the same as data in the django group
  bims/signals/__init__.py
  bims/signals/app.py
  bims/signals/group_profile.py
  core/settings/contrib.py
Labels: in review, review

#461 Disable i18n for admin page
  bims/api_urls.py
  bims/signals/app.py
  bims/urls.py
  core/urls.py
Labels: in review, review

#462 Fix adding flatpages does not work
  bims/templates/ckeditor/widget.html
Labels: in review

#463 Improve layer selector ux
  bims/static/css/map.css
  bims/static/img/transparency-icon.png
  bims/templates/map_page/map-templates.html
Labels: in review

#464 Option to remove collector filter
  bims/templates/map_page/map-templates.html
  bims/views/map.py
Labels: in review, review

#465 Update upload data in map control panel
  bims/static/css/map.css
  bims/templates/map_page/map-templates.html
Labels: in review
