Repository kartoza/django-bims, pull requests merged in 2018-06, with the labels that each got.

#16 Show base collection data in admin
  bims/admin.py
Labels: review

#17 Adapter to check password strength
  bims/adapters/__init__.py
  bims/adapters/account_adapter.py
  bims/static/js/form.js
  core/base_static/css/form.css
Labels: review

#15 Add basemap selection
  bims/static/css/map.css
  bims/static/js/app.js
  bims/static/js/libs/ol-layerswitcher/ol-layerswitcher.js
  bims/static/js/libs/ol-layerswitcher/ol3-layerswitcher.css
  bims/static/js/libs/ol-mapbox-style/olms.js
  bims/static/js/views/location_site.js
  bims/static/js/views/olmap.js
  bims/static/mapbox-style/dark-matter-gl-style.json
  bims/static/mapbox-style/klokantech-terrain-gl-style.json
  bims/static/mapbox-style/positron-gl-style.json
  bims/templates/map.html
  bims/views/map.py
Labels: review

#23 move olms to require
  bims/static/js/app.js
  bims/static/js/libs/ol-mapbox-style/olms.js
  bims/static/js/optimized.js
  bims/static/js/views/olmap.js
  bims/templates/map.html
Labels: review

#26 Move css from core to bims
  bims/static/css/account.css
  bims/static/css/base.css
  bims/static/css/fonts.css
  bims/static/css/form.css
  bims/static/fonts/glyphicons-halflings-regular.eot
  bims/static/fonts/glyphicons-halflings-regular.svg
  bims/static/fonts/glyphicons-halflings-regular.ttf
  bims/static/fonts/glyphicons-halflings-regular.woff
  bims/static/fonts/glyphicons-halflings-regular.woff2
  bims/static/fonts/open-sans-v13-latin-regular.woff
  bims/static/fonts/open-sans-v13-latin-regular.woff2
  core/base_static/css/core.css
Labels: review

#31 Search
  Makefile
  bims/api_views/search.py
  bims/indexes/__init__.py
  bims/indexes/biological_collection_record.py
  bims/indexes/location_site.py
  bims/management/commands/test_search.py
  bims/search_backends/__init__.py
  bims/search_backends/fuzzy_elastic_backend.py
  bims/search_backends/fuzzy_elastic_search_engine.py
  bims/search_indexes.py
  bims/serializers/bio_collection_record_doc_serializer.py
  bims/static/css/map.css
  bims/static/js/optimized.js
  bims/static/js/views/map_control_panel.js
  bims/templates/map.html
  bims/templates/search/indexes/bims/biologicalcollectionrecord_text.txt
  bims/urls.py
  core/settings/contrib.py
  core/settings/dev_docker.py
  core/settings/prod_docker.py
  core/settings/project.py
  core/settings/test_docker.py
  core/settings/test_travis.py
  core/urls.py
  deployment/docker-compose.yml
  deployment/docker/REQUIREMENTS.txt
Labels: review

#32 Add django-haystack in setup.py
  setup.py
Labels: review

#33 Add missing dependency
  setup.py
Labels: review

#30 Contact Us
  .travis.yml
  bims/templates/contactus/contact.html
  bims/templates/contactus/contact_notification_email.txt
  bims/templates/contactus/contact_success.html
  bims/templates/landing_page.html
  core/settings/contrib.py
  core/urls.py
  deployment/docker/REQUIREMENTS.txt
  setup.py
Labels: review

#21 add links managed in admin
  .gitignore
  bims/admin.py
  bims/migrations/0008_category_link.py
  bims/models/__init__.py
  bims/models/links.py
  bims/templates/links/links.html
  bims/templates/main_base.html
  bims/urls.py
  bims/views/links.py
  deployment/sites-enabled/README.md
  deployment/sites-enabled/default.conf
Labels: in progress, review

#35 Returns geometry in search result, also clickable search results
  bims/serializers/bio_collection_record_doc_serializer.py
  bims/serializers/location_site_detail_serializer.py
  bims/static/css/map.css
  bims/static/js/views/map_control_panel.js
  bims/static/js/views/olmap.js
  deployment/docker-compose.yml
  deployment/docker/REQUIREMENTS.txt
Labels: review

#37 Update Set Up Dev Environment Process.
  Makefile
  deployment/docker-compose.yml
  deployment/docker/Dockerfile
Labels: review

#38 Update search frontend
  bims/static/css/map.css
  bims/static/js/app.js
  bims/static/js/collections/search_result.js
  bims/static/js/models/search_result.js
  bims/static/js/views/map_control_panel.js
  bims/static/js/views/olmap.js
  bims/static/js/views/search.js
  bims/static/js/views/search_result.js
  bims/static/js/views/side_panel.js
  bims/templates/map.html
Labels: review

#36 Add species clustering
  bims/api_views/cluster_collection_by_taxon.py
  bims/tests/test_cluster_collection_by_taxon_views.py
  bims/urls.py
  bims/utils/cluster_point.py
Labels: review

#39 Update compiled js
  bims/static/js/collections/search_result.js
  bims/static/js/optimized.js
Labels: review

#40 Fix search request, show not found
  bims/static/js/collections/search_result.js
  bims/static/js/optimized.js
Labels: review

#28 Generate Model Documentation
  core/settings/contrib.py
  deployment/docker/REQUIREMENTS.txt
  docs/.editorconfig
  docs/README.md
  docs/docs/Makefile
  docs/docs/__init__.py
  docs/docs/conf.py
  docs/docs/index.rst
  docs/docs/install.rst
  docs/docs/make.bat
  setup.py
Labels: review

#41 Cluster frontend
  bims/api_views/cluster.py
  bims/api_views/cluster_collection_by_taxon.py
  bims/api_views/location_site.py
  bims/serializers/bio_collection_record_doc_serializer.py
  bims/serializers/boundary_serializer.py
  bims/static/css/map.css
  bims/static/js/collections/cluster.js
  bims/static/js/collections/cluster_biological.js
  bims/static/js/collections/location_site.js
  bims/static/js/models/cluster_biological.js
  bims/static/js/views/cluster.js
  bims/static/js/views/cluster_biological.js
  bims/static/js/views/olmap.js
  bims/static/js/views/search_result.js
  bims/static/js/views/side_panel.js
  bims/templates/map.html
  bims/tests/test_cluster_collection_by_taxon_views.py
  bims/urls.py
Labels: review

#45 update side panel
  bims/static/css/map.css
  bims/static/js/collections/search_result.js
  bims/templates/map.html
Labels: review

#44 Update search backend
  bims/api_views/search.py
  bims/indexes/__init__.py
  bims/indexes/biological_collection_record.py
  bims/indexes/location_site.py
  bims/indexes/taxon.py
  bims/models/iucn_status.py
  bims/serializers/bio_collection_record_doc_serializer.py
  bims/serializers/location_site_serializer.py
  bims/serializers/taxon_serializer.py
  bims/static/js/collections/search_result.js
  bims/static/js/views/olmap.js
  bims/static/js/views/search_result.js
  bims/templates/map.html
  bims/templates/search/indexes/bims/locationsite_text.txt
  bims/templates/search/indexes/bims/taxon_text.txt
Labels: review

#46 Update compiled js
  bims/static/css/map.css
  bims/static/js/collections/search_result.js
  bims/static/js/optimized.js
  deployment/docker/REQUIREMENTS.txt
Labels: review

#47 Update setup dev env document for pycharm
  README-dev.md
  README.rst
Labels: review

#48 Add full taxonomy
  Makefile
  bims/migrations/0009_auto_20180624_0821.py
  bims/models/taxon.py
  bims/utils/gbif.py
Labels: review

#42 Upload view for base collection record
  bims/forms/csv_upload.py
  bims/migrations/0009_csvdocument.py
  bims/models/csv_document.py
  bims/templates/csv_uploader.html
  bims/urls.py
  bims/views/csv_upload.py
Labels: review

#49 fix site detail on click
  bims/static/js/collections/location_site.js
Labels: review

#50 Update migration and compiled js
  bims/migrations/0010_merge_20180625_0607.py
  bims/static/js/optimized.js
  bims/views/csv_upload.py
Labels: review

#53 ABC not found on python 2
  bims/management/commands/update_boundary.py
Labels: review

#54 Fix csv upload for python 2.7
  bims/views/csv_upload.py
Labels: review

#55 Fix namespace url
  core/urls.py
Labels: review

#56 Python 2.7, Django 1.11
  .travis.yml
  bims/api_views/search.py
  bims/management/commands/update_boundary.py
  bims/models/taxon.py
  bims/urls.py
  bims/views/csv_upload.py
  core/settings/base.py
  core/urls.py
  deployment/docker/Dockerfile
  deployment/docker/REQUIREMENTS.txt
  example/views/__init__.py
Labels: review

#61 add readout mouse to map
  bims/static/css/map.css
  bims/static/js/views/olmap.js
Labels: review

#63 Update setup.py
  setup.py
Labels: review

#60 improve cluster query, add administrative boundary
  Makefile
  README.rst
  bims/api_views/cluster.py
  bims/management/commands/generate_boundary_geojson.py
  bims/migrations/0011_boundary_centroid.py
  bims/models/boundary.py
  bims/serializers/boundary_serializer.py
  bims/static/js/collections/cluster.js
  bims/static/js/views/basemap.js
  bims/static/js/views/boundary.js
  bims/static/js/views/cluster.js
  bims/static/js/views/layer_style.js
  bims/static/js/views/olmap.js
Labels: review

#64 Update compiled javascripts
  bims/static/js/optimized.js
Labels: review

#59 Create project setup
  .flake8
  .gitignore
  Makefile
  deployment/ansible/development/group_vars/all.sample.yml
  deployment/ansible/development/group_vars/all.travis.yml
  deployment/ansible/development/hosts
  deployment/ansible/development/roles/docker_compose/tasks/main.yml
  deployment/ansible/development/roles/docker_compose/templates/docker-compose.override.yml.j2
  deployment/ansible/development/roles/pycharm/files/__init__.py
  deployment/ansible/development/roles/pycharm/files/inject_python_interpreter.py
  deployment/ansible/development/roles/pycharm/files/inject_run_configurations.py
  deployment/ansible/development/roles/pycharm/tasks/main.yml
  deployment/ansible/development/roles/pycharm/templates/django-bims.iml
  deployment/ansible/development/roles/pycharm/templates/django-environment.xml.j2
  deployment/ansible/development/roles/pycharm/templates/python-interpreter/django-bims.xml.j2
  deployment/ansible/development/roles/pycharm/templates/remote-mappings.xml.j2
  deployment/ansible/development/roles/pycharm/templates/vcs.xml
  deployment/ansible/development/roles/pycharm/templates/workspace-configuration.xml.j2
  deployment/ansible/development/roles/pycharm/vars/generic/MacOSX.yml
  deployment/ansible/development/roles/pycharm/vars/generic/Ubuntu.yml
  deployment/ansible/development/site.yml
  deployment/docker-compose.yml
Labels: review

#65 Add Ansible Project Setup Readme.md
  Makefile
  README.rst
  deployment/ansible/README.md
  deployment/ansible/requirements.txt
Labels: review

#70 fix taxon_gbif_id null
  bims/serializers/bio_collection_record_doc_serializer.py
Labels: review

#73 fix side panel
  bims/serializers/bio_collection_serializer.py
  bims/static/css/map.css
  bims/static/img/base.svg
  bims/static/img/map-marker-highlight.png
  bims/static/js/collections/search_result.js
  bims/static/js/views/layer_style.js
  bims/static/js/views/olmap.js
  bims/static/js/views/side_panel.js
  bims/templates/map.html
Labels: review

#69 add toggle for mouse readaout
  bims/static/css/map.css
  bims/static/js/app.js
  bims/static/js/views/olmap.js
  bims/templates/map.html
Labels: review

#29 Bibliography management
  .gitignore
  bims/admin.py
  bims/exceptions.py
  bims/factories.py
  bims/forms/bibliography.py
  bims/management/commands/bibtex_import.py
  bims/migrations/0009_auto_20180621_0200.py
  bims/migrations/0012_merge_20180626_1630.py
  bims/models/__init__.py
  bims/models/bibliography.py
  bims/static/css/styles.css
  bims/templates/_layouts/base.html
  bims/templates/main_base.html
  bims/templates/td_biblio/bibliography_styles/ieeetr.html
  bims/templates/td_biblio/entry_import.html
  bims/templates/td_biblio/entry_item.html
  bims/templates/td_biblio/entry_list.html
  bims/templates/td_biblio/layouts/one_col.html
  bims/templates/td_biblio/layouts/sidebar_block.html
  bims/templates/td_biblio/layouts/three_cols.html
  bims/templates/td_biblio/layouts/two_cols_left_sidebar.html
  bims/templates/td_biblio/layouts/two_cols_right_sidebar.html
  bims/templates/td_biblio/partials/publication_list_by_year.html
  bims/templatetags/td_biblio.py
  bims/urls.py
  bims/utils/loaders.py
  bims/views/bibliography.py
  core/settings/project.py
  deployment/docker/REQUIREMENTS.txt
  setup.py
Labels: in progress

#72 don't call cluster update on location site from csv upload
  bims/models/biological_collection_record.py
  bims/models/location_site.py
  bims/utils/gbif.py
  bims/views/csv_upload.py
  core/settings/contrib.py
Labels: review

#68 add error handler
  bims/api_views/cluster.py
  bims/static/css/map.css
  bims/static/js/app.js
  bims/static/js/views/olmap.js
  bims/templates/map.html
Labels: review

#76 fix search error
  bims/serializers/bio_collection_record_doc_serializer.py
Labels: review
