Repository kartoza/django-bims, pull requests merged in 2018-07, with the labels that each got.

#62 update landing page and add filters
  bims/api_views/collector.py
  bims/api_views/search.py
  bims/static/css/base.css
  bims/static/css/map.css
  bims/static/css/navbar.css
  bims/static/js/app.js
  bims/static/js/collections/search_result.js
  bims/static/js/views/map_control_panel.js
  bims/static/js/views/search.js
  bims/templates/landing_page.html
  bims/templates/main_base.html
  bims/templates/map.html
  bims/urls.py
Labels: review

#81 Clean up code and fix navbar
  bims/static/css/base.css
  bims/static/css/contactus.css
  bims/static/css/map.css
  bims/static/css/navbar.css
  bims/static/js/app.js
  bims/static/js/optimized.js
  bims/templates/contactus/contact.html
  bims/templates/landing_page.html
  bims/templates/main_base.html
  bims/templates/map.html
Labels: review

#86 update cluster to use filters of records
  bims/admin.py
  bims/api_views/cluster_collection_by_taxon.py
  bims/static/js/collections/cluster_biological.js
  bims/static/js/collections/search_result.js
  bims/static/js/views/olmap.js
  bims/static/js/views/search.js
Labels: review

#88 Add router, trigger search from url
  bims/static/js/app.js
  bims/static/js/router.js
  bims/static/js/shared.js
  bims/static/js/views/search.js
  bims/static/js/views/side_panel.js
Labels: review

#89 Set min zoom and map extent
  bims/static/js/views/olmap.js
  core/settings/contrib.py
Labels: review

#85 Refactor User Model to use GeoNode's Profile Model
  .travis.yml
  Makefile
  bims/admin.py
  bims/migrations/0011_auto_20180702_0443.py
  bims/models/biological_collection_record.py
  bims/models/profile.py
  core/config_hook/apps.py
  core/settings/contrib.py
  core/urls.py
  deployment/ansible/development/group_vars/all.sample.yml
  deployment/ansible/development/group_vars/all.travis.yml
  deployment/docker/Dockerfile
Labels: review

#90 fix result not same with cluster and update search result
  bims/api_views/search.py
  bims/static/css/map.css
  bims/static/js/collections/search_result.js
  bims/static/js/views/search_result.js
  bims/templates/map.html
Labels: review

#93 add record detail when individual record is clicked
  bims/serializers/bio_collection_serializer.py
  bims/static/css/map.css
  bims/static/js/views/cluster_biological.js
  bims/static/js/views/layer_style.js
  bims/static/js/views/olmap.js
  bims/templates/map.html
Labels: review

#92 add user profile page
  bims/static/css/base.css
  bims/static/css/user_profile.css
  bims/static/img/default-user.svg
  bims/static/img/github-logo.svg
  bims/static/img/google-logo.png
  bims/templates/main_base.html
  bims/templates/user_profile.html
  bims/urls.py
  bims/views/user_profile.py
Labels: review

#95 merge cluster and location site source to be biodiversity source
  bims/static/js/views/basemap.js
  bims/static/js/views/cluster.js
  bims/static/js/views/cluster_biological.js
  bims/static/js/views/layer_style.js
  bims/static/js/views/location_site.js
  bims/static/js/views/olmap.js
Labels: review

#94 [WIP] Fix travis unittest
  .gitignore
  .travis.yml
  Makefile
  deployment/ansible/development/group_vars/all.travis.yml
  deployment/ansible/development/roles/docker_compose/templates/docker-compose.override.yml.j2
Labels: review

#96 Add non bio and layer control selector
  bims/static/css/map.css
  bims/static/js/optimized.js
  bims/static/js/views/layer_style.js
  bims/static/js/views/map_control_panel.js
  bims/static/js/views/olmap.js
  bims/static/js/views/olmap_layers.js
  bims/templates/map.html
Labels: review

#91 Update model documentation and update docs directory tree
  core/settings/contrib.py
  docs/Makefile
  docs/README.md
  docs/__init__.py
  docs/conf.py
  docs/docs/index.rst
  docs/index.rst
  docs/install.rst
  docs/make.bat
Labels: review

#97 add geocontext handler
  bims/static/css/map.css
  bims/static/js/views/geocontext.js
  bims/static/js/views/olmap.js
  bims/static/js/views/olmap_basemap.js
  bims/static/js/views/olmap_layers.js
  bims/static/js/views/side_panel.js
  bims/templates/map.html
Labels: review

#99 update site list to use cluster
  bims/api_views/location_site.py
  bims/models/location_site.py
  bims/serializers/location_site_detail_serializer.py
  bims/serializers/location_site_serializer.py
  bims/static/js/collections/location_site.js
  bims/static/js/views/location_site.js
  bims/static/js/views/olmap.js
  bims/urls.py
  bims/utils/cluster_point.py
Labels: review

#103 not use / on geojson administrative
  bims/static/js/optimized.js
  bims/static/js/views/boundary.js
Labels: review

#104 fix zoom not integer on cluster
  bims/api_views/cluster_collection_by_taxon.py
  bims/api_views/location_site.py
Labels: review

#105 remove non existent js
  bims/templates/td_biblio/entry_import.html
  bims/templates/td_biblio/entry_list.html
  bims/templates/td_biblio/layouts/three_cols.html
  bims/templates/td_biblio/layouts/two_cols_left_sidebar.html
  bims/templates/td_biblio/layouts/two_cols_right_sidebar.html
Labels: review

#101 show common name as title on the record popup detail
  bims/static/css/map.css
  bims/templates/map.html
Labels: review

#102 not call fetching collection if the layer is turned off
  bims/static/js/views/olmap.js
  bims/static/js/views/olmap_layers.js
Labels: review

#108 Update compiled js
  bims/api_views/location_site.py
  bims/static/js/optimized.js
Labels: review

#111 add under development page & custom navbar url
  bims/context_processor.py
  bims/static/img/underdevelopment.gif
  bims/templates/main_base.html
  bims/templates/under_development.html
  bims/urls.py
  bims/views/under_development.py
  core/settings/base.py
Labels: review

#112 Update csv upload
  bims/admin.py
  bims/static/css/csv_uploader.css
  bims/templates/csv_uploader.html
  bims/views/csv_upload.py
Labels: review

#113 fix collector has unscaped character on the name
  bims/static/js/optimized.js
  bims/static/js/views/search.js
Labels: review

#114 update UI
  bims/context_processor.py
  bims/static/css/map.css
  bims/static/css/navbar.css
  bims/static/js/libs/ol-layerswitcher/ol-layerswitcher.js
  bims/static/js/libs/ol-layerswitcher/ol3-layerswitcher.css
  bims/static/js/views/map_control_panel.js
  bims/templates/main_base.html
  bims/templates/map.html
Labels: review

#115 implement location filtered when search
  bims/api_views/cluster_collection.py
  bims/serializers/boundary_serializer.py
  bims/static/css/map.css
  bims/static/js/collections/cluster_biological.js
  bims/static/js/views/cluster.js
  bims/static/js/views/olmap.js
  bims/static/js/views/search.js
  bims/static/js/views/search_result.js
  bims/templates/map.html
  bims/urls.py
Labels: review

#117 Improve landing page load performance
  bims/static/js/creative.js
  bims/static/js/views/generate-donut-chart.js
  bims/templates/landing_page.html
  bims/templates/main_base.html
Labels: review

#120 Refactor production Dockerfile
  deployment/production/Dockerfile
  deployment/production/build.sh
  deployment/production/entry-point.sh
Labels: review

#122 Refactor production Dockerfile
  deployment/production/build.sh
  deployment/production/entry-point.sh
Labels: review

#123 Remove example module, we don't need it anymore
  core/settings/project.py
  core/urls.py
Labels: review

#124 Fix rebuild index error
  bims/indexes/biological_collection_record.py
  bims/indexes/location_site.py
  bims/indexes/taxon.py
Labels: review

#125 Small fix for docker build script
  deployment/production/build.sh
Labels: review

#128 Add lib resources
  .gitignore
  bims/static/lib/fonts/glyphicons-halflings-regular.eot
  bims/static/lib/fonts/glyphicons-halflings-regular.svg
  bims/static/lib/fonts/glyphicons-halflings-regular.ttf
  bims/static/lib/fonts/glyphicons-halflings-regular.woff
  bims/static/lib/fonts/glyphicons-halflings-regular.woff2
  bims/static/lib/fonts/open-sans-v13-latin-regular.woff
  bims/static/lib/fonts/open-sans-v13-latin-regular.woff2
  core/settings/contrib.py
Labels: review

#134 Try to fix tests
  Makefile
  bims/tests/model_factories.py
  bims/tests/test_profile.py
  core/config_hook/apps.py
  core/settings/base.py
Labels: review

#135 Update login page
  bims/static/css/account.css
  bims/static/css/form.css
  bims/templates/account/email_confirm.html
  bims/templates/account/login.html
  bims/templates/account/logout.html
  bims/templates/account/password_reset.html
  bims/templates/account/password_reset_done.html
  bims/templates/account/password_reset_from_key.html
  bims/templates/account/password_reset_from_key_done.html
  bims/templates/account/signup.html
  bims/templates/account/verification_sent.html
  bims/templates/socialaccount/snippets/provider_list.html
Labels: review

#136 Add gis catalogue link in navbar
  bims/templates/main_base.html
Labels: review

#132 add legend for nonbiodiversity layer
  bims/static/css/map.css
  bims/static/js/views/olmap_layers.js
  bims/templates/map.html
Labels: review

#131 update attribution for toposhet
  bims/static/js/views/olmap_basemap.js
Labels: review

#139 Fix gruntserver command
  bims/management/commands/gruntserver.py
  bims/static/js/optimized.js
Labels: review

#141 add model to hold non biodiversity list
  bims/admin.py
  bims/api_views/non_biodiversity_layer.py
  bims/migrations/0016_nonbiodiversitylayer.py
  bims/models/__init__.py
  bims/models/non_biodiversity_layer.py
  bims/serializers/non_biodiversity_layer_serializer.py
  bims/static/js/views/olmap_layers.js
  bims/templates/map.html
  bims/urls.py
Labels: review

#140 update filter view
  bims/admin.py
  bims/api_views/category_filter.py
  bims/api_views/cluster_collection.py
  bims/api_views/search.py
  bims/indexes/biological_collection_record.py
  bims/indexes/location_site.py
  bims/static/css/map.css
  bims/static/js/app.js
  bims/static/js/collections/cluster_biological.js
  bims/static/js/collections/search_result.js
  bims/static/js/libs/noUiSlider.11.1.0/nouislider.css
  bims/static/js/libs/noUiSlider.11.1.0/nouislider.js
  bims/static/js/libs/noUiSlider.11.1.0/nouislider.min.css
  bims/static/js/libs/noUiSlider.11.1.0/nouislider.min.js
  bims/static/js/router.js
  bims/static/js/views/olmap.js
  bims/static/js/views/search.js
  bims/static/js/views/side_panel.js
  bims/templates/map.html
  bims/urls.py
Labels: review

#145 update optimized.js
  bims/static/js/optimized.js
Labels: review

#147 Update model docs
  .gitignore
  core/settings/contrib.py
  docs/index.rst
Labels: review

#148 correct heading
  bims/templates/main_base.html
Labels: in review, review

#149 fix get extent records not ignoring bbox
  bims/api_views/cluster_collection.py
Labels: in review, review

#152 About page
  bims/admin.py
  bims/templates/flatpages/default.html
  bims/templates/landing_page.html
  core/settings/contrib.py
  core/urls.py
  deployment/docker/REQUIREMENTS.txt
  setup.py
Labels: in review, review

#154 Copy and modify restore geonode command
  .flake8
  bims/management/commands/restore_geonode.py
  bims/templates/base.html
  bims/templates/geonode_base.html
  core/settings/base.py
  core/settings/contrib.py
  deployment/docker-compose.yml
Labels: in review, review

#157 Update production docker build configuration
  deployment/production/Dockerfile
  deployment/production/REQUIREMENTS.txt
  deployment/production/build.sh
  deployment/production/entry-point.sh
Labels: in review, review

#158 fix activate user
  bims/urls.py
  bims/views/activate_user.py
Labels: in review, review

#156 Home page after logging in
  bims/templates/main_base.html
Labels: in review, review

#161 Locate by Coordinate
  bims/static/css/map.css
  bims/static/js/views/locate.js
  bims/static/js/views/map_control_panel.js
  bims/static/js/views/olmap.js
  bims/templates/map.html
Labels: in review, review

#143 fix mobile layout
  bims/static/css/landing_page.css
  bims/static/css/navbar.css
  bims/templates/carousel.html
  bims/templates/landing_page.html
  bims/templates/main_base.html
Labels: review

#162 Update gruntfile configuration for production
  deployment/production/Gruntfile.js
Labels: in review, review

#164 Fix gruntserver error.
  bims/static/js/optimized.js
  bims/static/js/views/olmap.js
Labels: in review, review

#160 Run update index and cluster on background
  Makefile
  bims/__init__.py
  bims/celery.py
  bims/tasks/__init__.py
  bims/tasks/collection_record.py
  bims/views/csv_upload.py
  core/settings/celery_settings.py
  deployment/docker-compose.yml
Labels: in review, review

#165 Fix pipeline error
  bims/templates/documents/document_thumb_upload.html
  bims/templates/layers/layer_metadata_upload.html
  bims/templates/layers/layer_replace.html
  bims/templates/layers/layer_style_upload.html
  bims/templates/upload/layer_upload.html
Labels: in review, review

#166 change background color panel
  bims/static/css/map.css
Labels: in review, review

#146 add validation page
  bims/api_views/get_biorecord.py
  bims/api_views/validate_object.py
  bims/static/css/non_validated_list.css
  bims/static/js/libs/datepicker/datepicker.css
  bims/static/js/libs/datepicker/datepicker.js
  bims/static/js/libs/datepicker/i18n/datepicker.en.js
  bims/static/js/views/map-review-validation.js
  bims/templates/main_base.html
  bims/templates/non_validated_list.html
  bims/urls.py
  bims/utils/user_permissions.py
  bims/views/non_validated_list.py
Labels: review

#170 Fix dbrestore command by @dimasciput.
  Makefile
Labels: in review, review

#169 add initial date range and fix cluster sometimes not show on initial map
  bims/static/js/views/olmap.js
  bims/static/js/views/olmap_layers.js
  bims/static/js/views/search.js
  bims/templates/main_base.html
  bims/templates/map.html
  bims/views/map.py
Labels: in review, review

#167 update location context document
  Makefile
  bims/admin.py
  bims/management/commands/update_location_context_documents.py
  bims/migrations/0025_locationsite_location_context_document.py
  bims/migrations/0026_auto_20180727_0851.py
  bims/models/__init__.py
  bims/models/location_context.py
  bims/models/location_site.py
  bims/templates/map.html
  bims/tests/model_factories.py
  bims/tests/test_models.py
  bims/views/bibliography.py
  bims/views/map.py
  deployment/ansible/development/group_vars/all.sample.yml
  deployment/ansible/development/group_vars/all.travis.yml
  deployment/docker-compose.yml
Labels: in review, review

#177 fix image url
  bims/templates/landing_page.html
  bims/templates/non_validated_list.html
Labels: in review, review

#174 change collector's verbose name to collector or observer
  bims/migrations/0025_auto_20180730_0523.py
  bims/models/biological_collection_record.py
  bims/templates/map.html
Labels: in progress, in review

#179 Add merge migration.
  bims/migrations/0027_merge_20180731_0334.py
Labels: in review, review

#163 Add Records Collection Downloader
  bims/api_views/cluster_collection_by_taxon.py
  bims/api_views/collection.py
  bims/serializers/bio_collection_serializer.py
  bims/serializers/taxon_serializer.py
  bims/static/css/map.css
  bims/static/js/collections/cluster_biological.js
  bims/static/js/views/data_downloader.js
  bims/static/js/views/map_control_panel.js
  bims/static/js/views/olmap.js
  bims/static/js/views/search_result.js
  bims/templates/map.html
  bims/tests/test_cluster_collection_by_taxon_views.py
  bims/urls.py
  deployment/docker/REQUIREMENTS.txt
Labels: in review, review

#173 Allow a user to select point or area locations for data upload
  bims/static/css/map.css
  bims/static/img/upload-marker-small.png
  bims/static/img/upload-marker.png
  bims/static/js/views/map_control_panel.js
  bims/static/js/views/olmap.js
  bims/static/js/views/upload_data.js
  bims/templates/map.html
  bims/urls.py
  bims/views/collection_upload.py
  bims/views/map.py
  deployment/docker-compose.yml
  deployment/docker/REQUIREMENTS.txt
  deployment/production/REQUIREMENTS.txt
Labels: in progress
