Repository kartoza/django-bims, pull requests merged in 2019-02, with the labels that each got.

#737 Integrate geoserver with django bims [In Progress]
  bims/api_views/search_version_2.py
  bims/migrations/0110_searchprocess_search_raw_query.py
  bims/models/search_process.py
  bims/static/js/collections/search_result.js
  bims/static/js/views/olmap.js
  bims/static/js/views/olmap_basemap.js
  bims/static/js/views/olmap_layers.js
  bims/static/js/views/search.js
  bims/tasks/search_version_2.py
  bims/templates/map_page/bims.html
  bims/views/map.py
Labels: do not merge, in review, review

#752 Add 0 rating to SASS biotope rating
  bims/templatetags/jsonify.py
  sass/static/css/form_page.css
  sass/templates/form_page.html
Labels: in review, review

#753 SASS Form header no longer uses acronyms
  sass/templates/form_page.html
Labels: in review, review

#738 Implemented a type-to-complete widget for the COLLECTOR and REFERENCE pane under the map's search toolbar
  bims/static/css/map.css
  bims/static/js/views/search.js
  bims/templates/map_page/map-templates.html
Labels: in review, review

#756 Integrate geoserver with django bims
  bims/api_urls.py
  bims/api_views/site_by_coord.py
  bims/static/js/collections/search_result.js
  bims/static/js/views/olmap.js
  bims/static/js/views/olmap_layers.js
Labels: in review, review

#755 Tidied up panel buttons
  bims/static/css/base.css
  bims/static/css/map.css
  bims/static/js/views/right_panel/location_site_detail.js
Labels: in review, review

#759 Get taxon list from river catchment code
  bims/api_urls.py
  bims/api_views/river_catchment.py
  bims/migrations/0110_auto_20190203_0849.py
  bims/migrations/0111_rivercatchment_location_sites.py
  bims/models/location_site.py
  bims/models/river_catchment.py
  bims/utils/river_catchments.py
Labels: in review, review

#757 Fix site detail single dashboard
  bims/api_views/location_site.py
  bims/api_views/search_version_2.py
  bims/api_views/site_by_coord.py
  bims/static/js/views/detail_dashboard/site_detail.js
  bims/static/js/views/olmap.js
  bims/static/js/views/search.js
Labels: in review, new_search, review

#762 Update taxon detail dashboard
  bims/api_urls.py
  bims/api_views/get_biorecord.py
  bims/api_views/search_version_2.py
  bims/migrations/0111_auto_20190204_1252.py
  bims/models/search_process.py
  bims/static/js/views/detail_dashboard/site_detail.js
  bims/static/js/views/detail_dashboard/taxon_detail.js
  bims/static/js/views/olmap.js
  bims/static/js/views/olmap_layers.js
  bims/templates/map_page/bims.html
  bims/templates/map_page/dashboard-templates.html
  core/settings/contrib.py
Labels: in review, review

#766 Fix SiteVisitTaxon importer
  sass/scripts/fbis_site_visit_taxon_importer.py
Labels: in review, review

#781 Fix dashboard not showing any site
  .gitignore
  bims/models/search_process.py
  bims/static/js/views/detail_dashboard/site_detail.js
  bims/static/js/views/detail_dashboard/taxon_detail.js
Labels: in review

#780 Refactored map-templates.html into multiple files
  bims/templates/map_page/bims.html
  bims/templates/map_page/dashboard-templates.html
  bims/templates/map_page/map-templates.html
  bims/templates/map_page/search-panel-templates.html
  bims/templates/map_page/side-panel-templates.html
Labels: in review, review

#782 Add data source
  bims/admin.py
  bims/migrations/0114_datasource.py
  bims/models/__init__.py
  bims/models/data_source.py
  bims/tests/model_factories.py
  bims/tests/test_auto_complete.py
  bims/urls.py
  bims/views/autocomplete_search.py
  sass/migrations/0034_sitevisit_data_source.py
  sass/models/site_visit.py
  sass/static/js/sass_form.js
  sass/templates/form_page.html
  sass/views/sass_form.py
Labels: in review, review

#783 SASS Metric calculations in SASS form
  sass/static/css/form_page.css
  sass/static/js/sass_form.js
  sass/templates/form_page.html
  sass/views/sass_form.py
Labels: in review, review

#785 Fix search by date
  bims/models/search_process.py
Labels: in review, review

#790 Better way to store location_context data
  bims/management/commands/format_location_context_document.py
  bims/migrations/0115_locationsite_location_context.py
  bims/models/location_site.py
  bims/tests/model_factories.py
  bims/utils/location_context.py
  core/settings/dev.py
Labels: in review, review

#795 Initial work on sass single site detailed dashboard
  bims/management/commands/update_location_context_documents.py
  bims/static/js/libs/moment.js
  sass/static/css/sass_dashboard.css
  sass/static/js/sass_dashboard.js
  sass/templates/sass_dashboard_single_site.html
  sass/urls.py
  sass/views/sass_dashboard.py
Labels: in review, review

#798 Add ecological_category and ecological_condition model
  Makefile
  sass/admin.py
  sass/management/commands/update_ecological_data.py
  sass/migrations/0035_sassecologicalcategory_sassecologicalcondition.py
  sass/models/__init__.py
  sass/models/sass_ecological_category.py
  sass/models/sass_ecological_condition.py
  sass/static/docs/ecological_category.csv
  sass/static/docs/ecological_condition.csv
Labels: in review, review

#754 Moved side pannel site dashboard and detail dashboard button to the top
  bims/static/js/views/right_panel/location_site_detail.js
Labels: in review, review

#799 Update add_location_context_group method
  bims/management/commands/add_location_context_group.py
  bims/models/location_site.py
  sass/views/sass_dashboard.py
Labels: in review, review

#800 SASS data download in SASS single site dashboard
  sass/serializers/__init__.py
  sass/serializers/sass_data_serializer.py
  sass/static/css/sass_dashboard.css
  sass/static/js/sass_dashboard.js
  sass/tasks/__init__.py
  sass/tasks/download_sass_data_site.py
  sass/templates/sass_dashboard_single_site.html
  sass/urls.py
  sass/views/download_sass_data_site.py
  sass/views/sass_dashboard.py
Labels: in review, review

#806 Add download charts in sass dashboard
  bims/static/js/libs/htmlToCanvas/html2canvas.js
  sass/static/css/sass_dashboard.css
  sass/static/js/sass_dashboard.js
  sass/templates/sass_dashboard_single_site.html
Labels: in review, review

#807 Additional table info in sass dashboard
  sass/static/js/sass_dashboard.js
  sass/templates/sass_dashboard_single_site.html
  sass/views/sass_dashboard.py
Labels: review

#809 Fix broken dashboard page if there is no sass data
  sass/static/js/sass_dashboard.js
  sass/templates/sass_dashboard_single_site.html
  sass/views/sass_dashboard.py
Labels: in review, review

#811 Initial template for SASS multiple sites dashboard
  sass/static/css/sass_dashboard.css
  sass/static/js/libs/pace-0.5.3/pace-theme.css
  sass/static/js/libs/pace-0.5.3/pace.min.js
  sass/static/js/sass_dashboard_multiple.js
  sass/templates/sass_dashboard_multiple_sites.html
  sass/urls.py
  sass/views/sass_dashboard_multiple.py
Labels: in review, review

#812 Add links to sass dashboard page
  bims/static/js/views/detail_dashboard/site_detail.js
  bims/static/js/views/right_panel/location_site_detail.js
  bims/templates/map_page/dashboard-templates.html
  sass/views/sass_dashboard_multiple.py
Labels: in review, review

#814 Add readonly sass form page
  sass/templates/form_only_read_page.html
  sass/urls.py
  sass/views/sass_form.py
Labels: in review, review

#816 Show sass records table
  bims/templatetags/jsonify.py
  sass/templates/sass_dashboard_single_site.html
  sass/views/sass_dashboard.py
Labels: in review, review

#817 Fix null in SASS taxa per biotope
  sass/static/js/sass_dashboard.js
Labels: in review, review

#818 Add sass summary table in multiple site sass dashboard
  sass/static/js/sass_dashboard.js
  sass/static/js/sass_dashboard_multiple.js
  sass/templates/sass_dashboard_multiple_sites.html
  sass/views/sass_dashboard.py
  sass/views/sass_dashboard_multiple.py
Labels: in review, review

#823 Sass taxa per biotope table in SASS multiple site dashboard
  sass/static/js/sass_dashboard_multiple.js
  sass/templates/sass_dashboard_multiple_sites.html
  sass/views/sass_dashboard_multiple.py
Labels: in review, review

#825 Biotope ratings chart
  sass/static/css/sass_dashboard.css
  sass/static/js/sass_dashboard_multiple.js
  sass/templates/sass_dashboard_multiple_sites.html
  sass/views/sass_dashboard_multiple.py
Labels: in review, review

#827 Add download sass button in multi site dashboard
  sass/serializers/sass_data_serializer.py
  sass/static/css/sass_dashboard.css
  sass/static/js/sass_dashboard.js
  sass/static/js/sass_dashboard_multiple.js
  sass/static/js/utils/download_csv.js
  sass/tasks/download_sass_data_site.py
  sass/templates/sass_dashboard_multiple_sites.html
  sass/templates/sass_dashboard_single_site.html
  sass/urls.py
  sass/views/download_sass_data_site.py
Labels: in review, review

#828 Add link to multi-site dashboard list of site
  sass/static/js/sass_dashboard_multiple.js
Labels: in review, review

#830 Add sass summary data download
  sass/serializers/sass_data_serializer.py
  sass/static/css/sass_dashboard.css
  sass/static/js/sass_dashboard.js
  sass/static/js/sass_dashboard_multiple.js
  sass/templates/sass_dashboard_multiple_sites.html
  sass/templates/sass_dashboard_single_site.html
  sass/urls.py
  sass/views/download_sass_data_site.py
Labels: in review, review

#831 Add download map as png button
  sass/static/css/sass_dashboard.css
  sass/static/js/sass_dashboard.js
  sass/static/js/sass_dashboard_multiple.js
  sass/templates/sass_dashboard_multiple_sites.html
  sass/templates/sass_dashboard_single_site.html
Labels: in review, review

#833 Show filter list
  sass/static/css/sass_dashboard.css
  sass/static/js/sass_dashboard_multiple.js
  sass/static/js/utils/filter_list.js
  sass/templates/sass_dashboard_multiple_sites.html
Labels: in review, review

#834 Add missing download map button
  sass/templates/sass_dashboard_multiple_sites.html
Labels: in review, review

#836 Add data source list view
  sass/static/css/sass_dashboard.css
  sass/static/js/sass_dashboard_multiple.js
  sass/templates/sass_dashboard_multiple_sites.html
  sass/templates/sass_dashboard_single_site.html
  sass/views/sass_dashboard.py
  sass/views/sass_dashboard_multiple.py
  sass/views/sass_form.py
Labels: in review, review

#838 Fix sass data inconsistencies in dashboard
  sass/templates/sass_dashboard_single_site.html
  sass/views/download_sass_data_site.py
  sass/views/sass_dashboard.py
  sass/views/sass_dashboard_multiple.py
Labels: in review, review

#839 Fix site detail sass dashboard button
  bims/static/js/views/detail_dashboard/site_detail.js
Labels: in review, review

#848 Ecological chart for single site SASS dashboard
  sass/static/docs/ecological_category.csv
  sass/static/js/sass_dashboard.js
  sass/templates/sass_dashboard_single_site.html
  sass/views/sass_dashboard.py
Labels: in review, review

#846 Group taxa in SASS taxa table in dashboard
  sass/static/css/sass_dashboard.css
  sass/static/js/sass_dashboard.js
  sass/views/sass_dashboard.py
Labels: in review, review

#849 Add description for proportion of sensitive to tolerant taxa
  sass/static/js/sass_dashboard.js
  sass/templates/sass_dashboard_single_site.html
Labels: in review, review

#854 Fix geocontext management command
  bims/management/commands/add_location_context_group.py
Labels: in review, review

#852 Add ecological charts in SASS multi sites dashboard
  bims/management/commands/add_location_context_group.py
  sass/static/css/sass_dashboard.css
  sass/static/js/ecological_chart.js
  sass/static/js/sass_dashboard_multiple.js
  sass/templates/sass_dashboard_multiple_sites.html
  sass/views/sass_dashboard_multiple.py
Labels: in review, review

#856 Add water and eco_group data in csv summary
  sass/serializers/sass_data_serializer.py
  sass/static/js/sass_dashboard.js
  sass/templates/sass_dashboard_single_site.html
  sass/views/sass_dashboard.py
Labels: in review, review

#821 Added rest of style guide variables for colours as well as heading topography
  core/base_static/css/core.css
Labels: in review, review

#858 Add function fetch all species data from gbif
  bims/management/commands/fetch_species_from_gbif.py
  bims/utils/fetch_gbif.py
  bims/utils/gbif.py
Labels: in review, review

#862 Group SASS taxa per biotope table
  sass/static/js/sass_dashboard_multiple.js
  sass/views/sass_dashboard_multiple.py
Labels: in review, review

#861 Import fish from the list
  bims/management/commands/fetch_species_from_gbif.py
  bims/scripts/__init__.py
  bims/scripts/import_fish_species_from_file.py
  bims/static/data/SA.Master.fish.species.csv
  bims/utils/fetch_gbif.py
Labels: in review, review

#863 Updated Species Overview pannel as per the new mockups
  bims/serializers/location_site_detail_serializer.py
  bims/static/css/detailed_dashboard.css
  bims/static/css/map.css
  bims/static/img/fish-2-black.png
  bims/static/img/fish-2-grey.png
  bims/static/js/views/right_panel/location_site_detail.js
  bims/static/js/views/right_panel/taxon_detail.js
  bims/static/js/views/side_panel.js
  bims/templates/_layouts/base.html
  bims/templates/main_base.html
  bims/templates/map_page/bims.html
  bims/templates/map_page/dashboard-templates.html
  bims/templates/map_page/map-templates.html
  bims/templates/map_page/side-panel-templates.html
Labels: in review, review

#867 Create spatial scale filter from GeoContext
  bims/admin.py
  bims/api_urls.py
  bims/api_views/spatial_scale_filter.py
  bims/migrations/0116_auto_20190226_0630.py
  bims/migrations/0117_auto_20190226_0646.py
  bims/models/__init__.py
  bims/models/spatial_scale.py
  bims/models/spatial_scale_group.py
  bims/utils/location_context.py
  sass/migrations/0036_auto_20190226_0630.py
Labels: in review, review
