Repository kartoza/django-bims, pull requests merged in 2019-01, with the labels that each got.

#619 [WIP] River catchment filtering
  bims/admin.py
  bims/api_urls.py
  bims/api_views/boundary.py
  bims/api_views/collection.py
  bims/api_views/river_catchment.py
  bims/indexes/biological_collection_record.py
  bims/indexes/location_site.py
  bims/management/commands/generate_river_catchment.py
  bims/migrations/0091_rivercatchment.py
  bims/models/__init__.py
  bims/models/river_catchment.py
  bims/static/css/map.css
  bims/static/js/collections/cluster_biological.js
  bims/static/js/collections/search_result.js
  bims/static/js/shared.js
  bims/static/js/views/filter_panel/spatial_filter.js
  bims/static/js/views/political_region.js
  bims/static/js/views/search.js
  bims/templates/main_base.html
  bims/templates/map_page/map-templates.html
  bims/utils/river_catchments.py
Labels: in review, review

#624 Fix river catchment filtering
  bims/api_views/collection.py
  bims/indexes/biological_collection_record.py
Labels: in review, review

#625 Add permalink icon
  bims/static/css/map.css
  bims/static/js/views/map_control_panel.js
  bims/templates/map_page/map-templates.html
Labels: in review, review

#626 Fix permalink not working in healthyrivers
  bims/static/js/views/map_control_panel.js
Labels: in review

#627 Move permalink button and change the title
  bims/static/js/views/map_control_panel.js
  bims/templates/map_page/map-templates.html
Labels: in review, review

#629 Updates from develop
  .flake8
  bims/admin.py
  bims/api_urls.py
  bims/api_views/boundary.py
  bims/api_views/collection.py
  bims/api_views/location_site.py
  bims/api_views/river_catchment.py
  bims/indexes/__init__.py
  bims/indexes/biological_collection_record.py
  bims/indexes/location_site.py
  bims/indexes/taxon.py
  bims/indexes/vernacular_names.py
  bims/management/commands/generate_river_catchment.py
  bims/management/commands/update_vernacular_taxa.py
  bims/migrations/0089_auto_20181219_0829.py
  bims/migrations/0090_auto_20181220_0747.py
  bims/migrations/0091_rivercatchment.py
  bims/models/__init__.py
  bims/models/location_site.py
  bims/models/river_catchment.py
  bims/models/search_process.py
  bims/models/taxonomy.py
  bims/models/vernacular_name.py
  bims/serializers/location_site_serializer.py
  bims/static/css/map.css
  bims/static/js/app.js
  bims/static/js/collections/cluster_biological.js
  bims/static/js/collections/search_result.js
  bims/static/js/router.js
  bims/static/js/shared.js
  bims/static/js/views/detail_dashboard/site_detail.js
  bims/static/js/views/detail_dashboard/taxon_detail.js
  bims/static/js/views/filter_panel/reference_category.js
  bims/static/js/views/filter_panel/spatial_filter.js
  bims/static/js/views/introjs-tutorial.js
  bims/static/js/views/map_control_panel.js
  bims/static/js/views/olmap.js
  bims/static/js/views/political_region.js
  bims/static/js/views/search.js
  bims/static/js/views/side_panel.js
  bims/templates/main_base.html
  bims/templates/map_page/bims.html
  bims/templates/map_page/dashboard-templates.html
  bims/templates/map_page/map-templates.html
  bims/templates/search/indexes/bims/vernacularname_text.txt
  bims/utils/gbif.py
  bims/utils/river_catchments.py
  bims/utils/search_process.py
  bims/views/autocomplete_search.py
  bims/views/map.py
Labels: in review, review

#630 Only use python 2.7 for travis
  .travis.yml
Labels: in review, review

#632 Import User table from rivers dump
  bims/admin.py
  bims/management/commands/import_fbis_database.py
  bims/migrations/0092_fbisuuid.py
  bims/migrations/0093_auto_20190107_0256.py
  bims/models/__init__.py
  bims/models/fbis_uuid.py
  bims/models/profile.py
  bims/tests/model_factories.py
  bims/tests/test_models.py
  deployment/docker/Dockerfile
  deployment/docker/REQUIREMENTS.txt
  deployment/production/Dockerfile
  deployment/production/REQUIREMENTS.txt
Labels: in review, review

#635 River, Site, SiteVisit importer
  bims/admin.py
  bims/management/commands/import_fbis_database.py
  bims/migrations/0094_locationsite_other_data.py
  bims/migrations/0095_auto_20190108_0725.py
  bims/migrations/0096_locationsite_river.py
  bims/migrations/0097_auto_20190109_0349.py
  bims/migrations/0098_auto_20190109_0518.py
  bims/migrations/0099_auto_20190109_0526.py
  bims/migrations/0100_auto_20190109_0645.py
  bims/models/fbis_uuid.py
  bims/models/location_site.py
  bims/models/profile.py
  core/settings/contrib.py
  deployment/docker/REQUIREMENTS.txt
  deployment/production/REQUIREMENTS.txt
  sass/__init__.py
  sass/admin.py
  sass/apps.py
  sass/enums/__init__.py
  sass/enums/canopy_cover.py
  sass/enums/water_level.py
  sass/enums/water_turbidity.py
  sass/management/__init__.py
  sass/management/commands/__init__.py
  sass/management/commands/import_fbis_database.py
  sass/migrations/0001_initial.py
  sass/migrations/0002_sitevisit.py
  sass/migrations/0003_auto_20190109_0659.py
  sass/migrations/0004_auto_20190109_0700.py
  sass/migrations/0005_sitevisit_location_site.py
  sass/migrations/__init__.py
  sass/models/__init__.py
  sass/models/river.py
  sass/models/site_visit.py
  sass/scripts/__init__.py
  sass/scripts/fbis_importer.py
  sass/scripts/fbis_river_importer.py
  sass/scripts/fbis_site_importer.py
  sass/scripts/fbis_site_visit_importer.py
  sass/scripts/fbis_user_importer.py
  sass/tests.py
  sass/views.py
Labels: in review, review

#590 Added About Us page as flat page
  bims/migrations/0101_auto_20190109_1122.py
  bims/templates/navigation_bar.html
  core/settings/contrib.py
Labels: in review, review

#639 About us page
  bims/migrations/0101_auto_20190109_1122.py
  bims/templates/navigation_bar.html
  core/settings/contrib.py
Labels: in review, review

#655 Taxon sass importer
  bims/admin.py
  bims/enums/taxonomic_group_category.py
  bims/migrations/0101_auto_20190110_0533.py
  bims/migrations/0102_merge_20190111_0728.py
  bims/migrations/0103_move_sass_biotope_model.py
  bims/migrations/0104_auto_20190111_0928.py
  bims/migrations/0105_biotope_biotope_component.py
  bims/models/__init__.py
  bims/models/biotope.py
  bims/utils/gbif.py
  sass/admin.py
  sass/management/commands/import_fbis_database.py
  sass/migrations/0012_sasstaxon.py
  sass/migrations/0013_auto_20190110_0631.py
  sass/migrations/0014_auto_20190111_0809.py
  sass/migrations/0015_update_relations.py
  sass/migrations/0016_delete_old_model_from_the_state.py
  sass/models/__init__.py
  sass/models/sass_biotope_fraction.py
  sass/models/sass_taxon.py
  sass/scripts/fbis_importer.py
  sass/scripts/fbis_sass_biotope_importer.py
  sass/scripts/fbis_site_visit_sass_biotope_importer.py
  sass/scripts/fbis_taxon_group_importer.py
  sass/scripts/fbis_taxon_importer.py
Labels: in review, review

#658 Site visit taxon
  bims/migrations/0106_auto_20190114_0705.py
  bims/migrations/0107_biologicalcollectionrecord_source_collection.py
  bims/models/biological_collection_record.py
  bims/utils/gbif.py
  sass/admin.py
  sass/enums/channel_type.py
  sass/management/commands/import_fbis_database.py
  sass/migrations/0017_auto_20190114_0209.py
  sass/migrations/0018_sitevisitbiotopetaxon_date.py
  sass/migrations/0019_sassvalidationstatus.py
  sass/migrations/0020_sitevisittaxon.py
  sass/migrations/0021_sitevisit_channel_type.py
  sass/models/__init__.py
  sass/models/abstract_additional_data.py
  sass/models/sass_biotope_fraction.py
  sass/models/sass_validation_status.py
  sass/models/site_visit.py
  sass/models/site_visit_biotope_taxon.py
  sass/models/site_visit_taxon.py
  sass/models/taxon_abundance.py
  sass/scripts/fbis_importer.py
  sass/scripts/fbis_sass_validation_status_importer.py
  sass/scripts/fbis_site_visit_biotope_taxon_importer.py
  sass/scripts/fbis_site_visit_importer.py
  sass/scripts/fbis_site_visit_taxon_importer.py
  sass/scripts/fbis_taxon_abudance_importer.py
Labels: in review, review

#673 Import SiteVisitChem and Chem
  sass/admin.py
  sass/enums/chem_unit.py
  sass/management/commands/import_fbis_database.py
  sass/migrations/0022_chem.py
  sass/migrations/0023_sitevisitchem.py
  sass/models/__init__.py
  sass/models/chem.py
  sass/models/site_visit_chem.py
  sass/scripts/fbis_chem_importer.py
  sass/scripts/fbis_site_visit_biotope_taxon_importer.py
  sass/scripts/fbis_site_visit_chem_importer.py
  sass/scripts/fbis_site_visit_sass_biotope_importer.py
  sass/scripts/fbis_site_visit_taxon_importer.py
Labels: in review, review

#675 Majority of changes as requested by Toni for the Intro.js (Only Tip 12 outstanding)
  bims/static/css/map.css
  bims/static/js/views/introjs-tutorial.js
  bims/static/js/views/olmap.js
  bims/static/js/views/search.js
  bims/templates/map_page/map-templates.html
Labels: in review, review

#676 Update admin view
  bims/admin.py
  sass/admin.py
Labels: in review, review

#677 Fix security vulnerabilities
  deployment/docker/REQUIREMENTS.txt
  deployment/production/REQUIREMENTS.txt
  setup.py
Labels: in review, review

#682 Base templates for sass form
  core/settings/contrib.py
  core/urls.py
  sass/static/css/form_page.css
  sass/templates/form_page.html
  sass/urls.py
  sass/views.py
  sass/views/__init__.py
  sass/views/form.py
Labels: in review, review

#689 Fix search api
  bims/api_views/collection.py
  bims/indexes/biological_collection_record.py
  bims/management/commands/update_vernacular_taxa.py
Labels: in review, review

#691 Add SASS 5 Form and Sheet models
  core/urls.py
  sass/admin.py
  sass/enums/sass5_rating.py
  sass/migrations/0024_sass5sheet.py
  sass/migrations/0025_auto_20190117_1007.py
  sass/migrations/0026_sass5record.py
  sass/models/__init__.py
  sass/models/sass5_record.py
  sass/models/sass5_sheet.py
Labels: in review, review

#692 Update sass record model
  sass/admin.py
  sass/migrations/0027_auto_20190118_0307.py
  sass/models/sass5_record.py
Labels: in review, review

#704 Change gruntfile path for production
  deployment/production/Gruntfile.js
Labels: in review, review

#693 Grab taxon data from sass sheet and display it in template
  bims/admin.py
  bims/enums/taxonomic_rank.py
  bims/migrations/0108_auto_20190121_0415.py
  bims/tests/test_selenium.py
  bims/utils/gbif.py
  core/settings/test_docker.py
  sass/management/commands/update_sass5_taxon.py
  sass/migrations/0028_auto_20190118_0614.py
  sass/migrations/0029_auto_20190121_0415.py
  sass/models/sass5_record.py
  sass/models/sass5_sheet.py
  sass/models/sass_taxon.py
  sass/static/css/form_page.css
  sass/static/img/fbis_sass_logo.png
  sass/static/js/sass_5_record.js
  sass/templates/form_page.html
  sass/urls.py
  sass/views/form.py
Labels: review

#706 SASS List and Update view
  bims/context_processor.py
  bims/static/css/map.css
  bims/static/js/views/right_panel/location_site_detail.js
  bims/templates/map_page/bims.html
  bims/templates/navigation_bar.html
  core/settings/contrib.py
  sass/static/css/form_page.css
  sass/static/js/sass_5_record.js
  sass/templates/form_page.html
  sass/templates/sass_list_page.html
  sass/urls.py
  sass/views/form.py
  sass/views/sass_list.py
Labels: in review, review

#708 Improve filters in admin Permission view
  bims/admin.py
Labels: in review, review

#709 Fix broken migrations in LEDET
  bims/migrations/0092_fbisuuid.py
Labels: in review, review

#712 Change geonode people page to original theme
  bims/templates/avatar/add.html
  bims/templates/avatar/change.html
  bims/templates/avatar/confirm_delete.html
  bims/templates/people/profile_base.html
  bims/templates/people/profile_bims_base.html
  bims/templates/people/profile_detail.html
Labels: in review, review

#711 Final changes implemented to intro.js as requested
  bims/static/js/views/introjs-tutorial.js
Labels: in review, review

#715 Fix tracking page
  bims/conf.py
  bims/templates/tracking/dashboard.html
  bims/views/tracking.py
  core/settings/contrib.py
Labels: in review, review

#718 Fixed styling on layer abstract layer so longer abstracts can be shown
  bims/static/css/map.css
Labels: in review, review

#729 Add settings values to enable/disable filter element
  bims/context_processor.py
  bims/static/css/map.css
  bims/templates/map_page/map-templates.html
  bims/views/map.py
  core/settings/contrib.py
Labels: in review, review

#733 Fix validators email
  bims/api_views/send_notification_to_validator.py
  bims/migrations/0109_auto_20190128_0410.py
  bims/models/biological_collection_record.py
  bims/static/js/views/right_panel/validate_data_detail.js
  bims/tasks/collection_record.py
  bims/templates/map_page/map-templates.html
Labels: in review, review

#721 Confirm names and order of search layers
  bims/templates/map_page/map-templates.html
  bims/views/map.py
Labels: in review, review

#734 Improve identify features
  bims/api_views/get_feature_info.py
  bims/static/css/map.css
  bims/static/js/shared.js
  bims/static/js/views/olmap_layers.js
Labels: in review, review

#728 Add scroll functionality and other styling so one can move down when search is expanded
  bims/static/css/map.css
Labels: in review, review

#732 Changed SASS form input to use radio buttons instead of a select box
  bims/templatetags/jsonify.py
  sass/static/css/form_page.css
  sass/static/js/sass_5_record.js
  sass/templates/form_page.html
  sass/views/form.py
Labels: in review, review

#720 Search version 2
  bims/api_urls.py
  bims/api_views/search_version_2.py
  bims/api_views/site_search_result.py
  bims/indexes/__init__.py
  bims/indexes/location_site.py
  bims/models/boundary.py
  bims/models/search_process.py
  bims/static/css/base.css
  bims/static/css/map.css
  bims/static/js/collections/search_result.js
  bims/static/js/router.js
  bims/static/js/shared.js
  bims/static/js/tests/biologicalSpec.js
  bims/static/js/utils/events_connector.js
  bims/static/js/views/search.js
  bims/static/js/views/search_result.js
  bims/tasks/__init__.py
  bims/tasks/search_version_2.py
  bims/templates/map_page/map-templates.html
Labels: in review, review

#727 Added a PNG "stamp" to the bottom of the downloadable graphs.
  bims/static/img/bims-stamp.png
  bims/static/js/views/detail_dashboard/site_detail.js
  bims/static/js/views/detail_dashboard/taxon_detail.js
Labels: in review, review
